### ISSUE TITLE
Issue while vignettes in package DATA606

### ISSUE THREAD

**Issue by rajk11040** [jbryer/DATA606Spring2018#2]
Hi
I am having an issue while installing the software on my PC (as per the link http://data606.net/course-overview/software/). I was able to complete all other steps prior to this successfully.

I tried to attached screenshot but got an error. 
Basically 
> vignette(package='DATA606') results in "no vignettes found"

Please see below and advice.

> library('DATA606')

Welcome to CUNY DATA606 Statistics and Probability for Data Analytics 
This package is designed to support this course. The text book used 
is OpenIntro Statistics, 3rd Edition. You can read this by typing 
vignette('os3') or visit www.OpenIntro.org. 
 
The getLabs() function will return a list of the labs available. 
 
The demo(package='DATA606') will list the demos that are available. 

Attaching package: ‘DATA606’

The following object is masked from ‘package:utils’:

    demo

> vignette(package='DATA606')
no vignettes found
> vignette('os3')
Warning message:
vignette ‘os3’ not found

**Comment by jbryer** [comment]
Did you call the vignette function before or after the library(DATA606)
command? It needs to be after. That is:

```
library(DATA6060)
vignette(package='DATA606')
```

**Comment by rajk11040** [comment]
I called it after the library function.... 
Please see below... I am trying to paste the response directly from the console window.
Please advice.
thanks Raj

> library('DATA606')  
Welcome to CUNY DATA606 Statistics and Probability for Data Analytics  This package is designed to support this course. The text book used  is OpenIntro Statistics, 3rd Edition. You can read this by typing  vignette('os3') or visit www.OpenIntro.org.    The getLabs() function will return a list of the labs available.    The demo(package='DATA606') will list the demos that are available.   Attaching package: ‘DATA606’  The following object is masked from ‘package:utils’:      demo  
> vignette(package='DATA606') 
no vignettes found
--
 
> | >
>

**Comment by rajk11040** [comment]
![vignetteerror1](https://user-images.githubusercontent.com/32854749/35765064-fa232202-088a-11e8-9886-64397e33707b.JPG)

**Comment by rajk11040** [comment]
Nevermind... I think I figured it out... 
I was expecting it to return list of vignettes .... but I guess "no vignettes found" is ok
I was able to start lab despite the earlier message.
Sorry as I was confused with this.
