### ISSUE TITLE
Question about simulations

### ISSUE THREAD

**Issue by zachdravis** [jbryer/DATA606Spring2018#4]
While doing lab2 I kept thinking about when comparing the simulated streaks data to Kobe's data how it would be most accurate to run the simulation several times and then take the average of the data (the average frequency of each streak length).  This way law of large numbers plays in and the simulation becomes more representative of what true independence would look like (minimizes chance).  Could anyone shed any light on how to do this in R?

**Comment by jbryer** [comment]
The simplest way is to use a for loop. I will cover this at an upcoming
meetup too.
